### ISSUE TITLE
404 Page Not Found error

### ISSUE THREAD

**Issue by ksuuk** [sussexlabs/monami#12]
When adding/editing:

host, url path /hosts/add
checks, url path /checks/add
edit host, url path /hosts/configure/*
edit profie, url path /profile

All I get is error:

404 Page Not Found
The page you requested was not found.

**Comment by labrack** [comment]
Not a bug, those controller functions just haven’t been added yet :)

**Comment by ksuuk** [comment]
Prr, then how and for what are You using this software (http://www.sussexlabs.net/services/management/), when it does not allow adding host or checks? 

Also http://monami.io/ domain does not exist.

**Comment by labrack** [comment]
It’s true, this project has kind of...died out. While monami was being developed, other monitoring-as-a-service sites kind of got better at it. We’re keeping this online now mostly for posterity and in case people want to fork it and finish It themselves

**Comment by ksuuk** [comment]
Sad, as I'm looking simple php based remote server & services uptime monitor with basic GUI. All I need, is to check tcp/udp port and ping host and send notification email, when something is down and when something is up again.

**Comment by labrack** [comment]
Check out https://github.com/phpservermon/phpservermon  ...  or feel free to send in some PRs to this project with fixes and we’ll be happy to merge them in :)

**Comment by ksuuk** [comment]
I thought you'd recommend it. But it sucks and a big time. It does not show service per status, or support service groups, no config cloning options etc. So one server, 10 services = 10 identical status lines. Can't imagine how anybody can use it. :( 

And yes, I added these issues to them also.
